spring:

  #MySQL数据库
  datasource:
    url: jdbc:mysql://localhost:3306/PaperPushSystem?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    #使用阿里数据源
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    validationQuery: select 'x'
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat
  #elasticsearch jpa
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
  #jsp前缀后缀
  mvc:
    view:
      prefix: /
      suffix: .jsp
  #elasticsearch
#  elasticsearch:
#    jest:
#      uris: http://localhost:9200
#      username: elastic
#      read-timeout: 6s
#      password: changeme




server:
  port: 8090


mail:
  from: paperpushsystem@163.com
  authorizationCode: paper123456
  host: smtp.163.com

mybatis:
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true

#pagehelper分页插件
pagehelper:
  # 配置数据库方言，不配置也行，分页插件会自动检测当前的数据库链接，自动选择合适的分页方式，
  # 使用 SqlServer2012 数据库时，需要手动指定为 sqlserver2012，否则会使用 SqlServer2005 的方式进行分页。
  helper-dialect: mysql
  # 分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页，
  # pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
  reasonable: true
  # 默认值为 false，当该参数设置为 true 时，如果 pageSize=0 或者 RowBounds.limit = 0 ,
  # 就会查询出全部的结果（相当于没有执行分页查询，但是返回结果仍然是 Page 类型）
  page-size-zero: true

# 定义分页常量
page:
  # 默认当前页
  currentPage: 1
  # 默认页面大小
  pageSize: 10
  # 每页最大行数
  maxSize: 30

md5:
  salt: 123456
